name: agent
version: 0.0.0.1
license: MIT

dependencies:
  - base

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-kind-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Blammo
    - aeson
    - amazonka
    - amazonka-autoscaling
    - amazonka-sqs
    - bytestring
    - composition-extra
    - conduit
    - conduit-extra
    - envparse
    - github
    - hedis
    - http-conduit
    - http-types
    - immortal
    - microlens-platform
    - monad-logger
    - optparse-applicative
    - relude
    - resourcet
    - text
    - time
    - typed-process
    - unliftio
    - unliftio-core

    # For GitHub extension modules
    - jwt
    - tagged

    # Database.Redis.TLS
    - errors
    - data-default-class
    - tls

executables:
  agent:
    main: Main.hs
    source-dirs: app
    dependencies:
      - agent
# tests:
#   doctest:
#     main: Main.hs
#     source-dirs: doctest
#     dependencies:
#       - doctest
#   spec:
#     main: Spec.hs
#     source-dirs: test
#     dependencies:
#       - hspec
#       - agent
