name: agent
version: 0.0.0.1
license: MIT

dependencies:
  - base
  - rio

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - amazonka
    - amazonka-autoscaling
    - amazonka-ecs
    - amazonka-sqs
    - bytestring
    - composition-extra
    - conduit
    - conduit-extra
    - datadog
    - github
    - hedis
    - http-conduit
    - http-types
    - lens
    - lens-aeson
    - load-env
    - optparse-applicative
    - monad-validate
    - parsec
    - random
    - resource-pool

    # For GitHub extension modules
    - jwt
    - tagged
    - text
    - time
    - unliftio

executables:
  agent:
    main: Main.hs
    source-dirs: app
    dependencies:
      - agent
# tests:
#   doctest:
#     main: Main.hs
#     source-dirs: doctest
#     dependencies:
#       - doctest
#   spec:
#     main: Spec.hs
#     source-dirs: test
#     dependencies:
#       - hspec
#       - agent
