resolver: lts-21.13
extra-deps:
  - amazonka-2.0
  - amazonka-core-2.0
  - amazonka-autoscaling-2.0
  - amazonka-s3-2.0
  - amazonka-sqs-2.0
  - amazonka-sso-2.0
  - amazonka-sts-2.0
  - amazonka-mtl-0.1.1.0
