resolver: lts-19.8
extra-deps:
  - github: brendanhay/amazonka
    commit: f73a957d05f64863e867cf39d0db260718f0fadd # main, as of SSO support
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-autoscaling
      - lib/services/amazonka-ecs
      - lib/services/amazonka-sqs
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts

  # https://github.com/hasura/monad-validate/pull/5
  - github: LeapYear/monad-validate
    commit: 5b181b7c57d6e2c975c533b0a0072e9aeb15fb99

  # For weeder-2.3.0
  - algebraic-graphs-0.5
